phrase:
  project_id: dfb94e56588822f0b46438ed822d1b4a

  push:
    sources:
      - file: ./src/en.json
        params:
          file_format: simple_json
          locale_id: en

  pull:
  targets:
    - file: ./src/en.json
      params:
        file_format: simple_json
