phrase:
  access_token: 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

  push:
    sources:
      - file: .\src\<locale_name>.json
        params:
          file_format: simple_json
          locale_id: en

    pull:
    targets:
      - file: .\src\<locale_name>.json
        params:
          file_format: simple_json
