phrase:
  access_token: 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
  project_id: dfb94e56588822f0b46438ed822d1b4a

  push:
    sources:
      - file: ./src/<locale_name>.json
        params:
          file_format: simple_json
          locale_id: en

    pull:
    targets:
      - file: ./src/<locale_name>.json
        params:
          file_format: simple_json
